// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOcrsBwgjs1NBfG0cX_ZumKHuvEEpwl94',
    appId: '1:1017041180812:web:d47d5c181dad640d6d83a9',
    messagingSenderId: '1017041180812',
    projectId: 'ecommerce-app-aa849',
    authDomain: 'ecommerce-app-aa849.firebaseapp.com',
    storageBucket: 'ecommerce-app-aa849.appspot.com',
    measurementId: 'G-KN0D9HBT0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW0Vz1e6ly0jvogLFzLn8Gnhh6N-ZSqBs',
    appId: '1:1017041180812:android:097d1a7d773a742d6d83a9',
    messagingSenderId: '1017041180812',
    projectId: 'ecommerce-app-aa849',
    storageBucket: 'ecommerce-app-aa849.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47w9G5sj6OU6aQ8-2E8Oh8IOwBxuYUU8',
    appId: '1:1017041180812:ios:9a68339a794b239a6d83a9',
    messagingSenderId: '1017041180812',
    projectId: 'ecommerce-app-aa849',
    storageBucket: 'ecommerce-app-aa849.appspot.com',
    iosClientId: '1017041180812-sbg5fptg3k4937u68sk30kre0rnma1bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47w9G5sj6OU6aQ8-2E8Oh8IOwBxuYUU8',
    appId: '1:1017041180812:ios:b0e6352766f032556d83a9',
    messagingSenderId: '1017041180812',
    projectId: 'ecommerce-app-aa849',
    storageBucket: 'ecommerce-app-aa849.appspot.com',
    iosClientId: '1017041180812-9q4g1haeb66ogju574t4u4ev83m51jaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerse.RunnerTests',
  );
}
